# Generated by Django 5.0.6 on 2026-09-14 16:54

import django.db.models.deletion
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Tech & Engineering', 'Tech & Engineering'), ('Business & Administration', 'Business & Administration'), ('Hospitality & Tourism', 'Hospitality & Tourism'), ('Health & Medicine', 'Health & Medicine'), ('Education & Teaching', 'Education & Teaching'), ('Sales & Marketing', 'Sales & Marketing')], max_length=60)),
                ('company', models.CharField(help_text='Display name shown on the card.', max_length=200)),
                ('location', models.CharField(default='Nairobi, Kenya', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.JSONField(blank=True, default=list, help_text='List of strings. In admin, edit as a JSON array.')),
                ('qualifications', models.JSONField(blank=True, default=list, help_text='List of strings. In admin, edit as a JSON array.')),
                ('source', models.CharField(default='Direct Listing', help_text='e.g. Daily Nation, Gazette, Company Portal', max_length=120)),
                ('application_type', models.CharField(choices=[('CUSTOM', 'Custom method (free text)'), ('LINK', 'External link'), ('EMAIL', 'Email application'), ('STANDARD', 'In-app: CV + Cover Letter'), ('CV_ONLY', 'In-app: CV or Cover Letter')], default='CUSTOM', max_length=20)),
                ('application_target', models.CharField(blank=True, help_text='URL or email — only used for LINK / EMAIL types.', max_length=300)),
                ('application_custom_text', models.TextField(blank=True, help_text='Free-text method of application. URLs and emails auto-linkify.')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=jobs.models.default_expiry)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_by_email', models.EmailField(blank=True, max_length=254)),
                ('organization', models.ForeignKey(blank=True, help_text='Leave blank for Weraiko Direct / global posts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('cover_letter', models.TextField(blank=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='applications/cvs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
