# Generated by Django 5.0.6 on 2026-09-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Tech & Engineering', 'Tech & Engineering'), ('Business & Administration', 'Business & Administration'), ('Hospitality & Tourism', 'Hospitality & Tourism'), ('Health & Medicine', 'Health & Medicine'), ('Education & Teaching', 'Education & Teaching'), ('Sales & Marketing', 'Sales & Marketing'), ('Transport & Logistics', 'Transport & Logistics'), ('Security & Safety', 'Security & Safety')], max_length=60),
        ),
    ]
