# Generated by Django 5.0.6 on 2026-09-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('CV & Resume', 'CV & Resume'), ('Interviews', 'Interviews'), ('Salary', 'Salary'), ('Career Growth', 'Career Growth'), ('Job Search', 'Job Search'), ('Workplace', 'Workplace')], max_length=60)),
                ('excerpt', models.CharField(help_text='Short summary shown on the guides index.', max_length=320)),
                ('content', models.TextField(help_text='Main article. Use blank lines to separate paragraphs.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='guide_covers/')),
                ('author', models.CharField(default='Weraiko Team', max_length=120)),
                ('read_minutes', models.PositiveIntegerField(default=4, help_text='Approx read time in minutes.')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guide',
                'verbose_name_plural': 'Guides',
                'ordering': ['-published_at'],
            },
        ),
    ]
