# Generated by Django 5.0.6 on 2026-09-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, help_text='Application closing date, if specified.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, choices=[('CERTIFICATE', 'Certificate'), ('DIPLOMA', 'Diploma'), ('BACHELOR', "Bachelor's Degree"), ('MASTERS', "Master's Degree"), ('PHD', 'PhD')], help_text='Minimum education required, if specified.', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='full_description',
            field=models.TextField(blank=True, help_text='Full job description as written by the employer. Use ## for headings, blank lines to separate paragraphs. This is the long-form content shown on the detail page.'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('REMOTE', 'Remote')], default='FULL_TIME', help_text='Full Time, Part Time, Contract, Internship, or Remote.', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.CharField(blank=True, help_text='e.g. Ksh 50,000 – 80,000. Leave blank if not disclosed.', max_length=120),
        ),
        migrations.AlterField(
            model_name='guide',
            name='content',
            field=models.TextField(help_text='Main article. Use ## for headings, blank lines to separate paragraphs.'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='excerpt',
            field=models.CharField(max_length=320),
        ),
        migrations.AlterField(
            model_name='guide',
            name='read_minutes',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, help_text='Short 1-2 sentence summary shown on the list page.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=models.JSONField(blank=True, default=list, help_text='List of strings — JSON array.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list, help_text='List of strings — JSON array.'),
        ),
    ]
