# Generated by Django 5.0.6 on 2026-09-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_deadline_job_education_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='cover_image',
        ),
    ]
