services:
  - type: web
    name: weraiko-api
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn weraiko.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.13.0"
      - key: DATABASE_URL
        fromDatabase:
          name: weraiko-db
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        value: owner
      - key: DJANGO_SUPERUSER_EMAIL
        value: owner@weraiko.co.ke
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false

databases:
  - name: weraiko-db
    plan: free